default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  local_infile: true

development:
  <<: *default
  database: rails416_sandbox_development

test:
  <<: *default
  database: rails416_sandbox_test

production:
  <<: *default
  database: rails416_sandbox

legacy:
  <<: *default
  database: estate
